version: '3.8'

services:
  supabase-db:
    image: supabase/postgres:15.1.0.89
    restart: unless-stopped
    ports:
      - "54322:5432"
    env_file:
      - .env.docker-compose
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./volumes/db:/var/lib/postgresql/data

  supabase-rest:
    image: postgrest/postgrest:v11.2.0
    restart: unless-stopped
    ports:
      - "54340:3000"
    env_file:
      - .env.docker-compose
    environment:
      PGRST_DB_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@supabase-db:5432/${POSTGRES_DB}
      PGRST_DB_ANON_ROLE: ${PGRST_DB_ANON_ROLE}
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET}
    depends_on:
      - supabase-db

  supabase-auth:
    image: supabase/gotrue:v2.149.0
    restart: unless-stopped
    ports:
      - "54341:9999"
    env_file:
      - .env.docker-compose
    environment:
      GOTRUE_SITE_URL: ${GOTRUE_SITE_URL}
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: ${GOTRUE_API_PORT}
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@supabase-db:5432/${POSTGRES_DB}
      GOTRUE_JWT_SECRET: ${GOTRUE_JWT_SECRET}
      GOTRUE_JWT_EXP: ${GOTRUE_JWT_EXP}
    depends_on:
      - supabase-db

  supabase-studio:
    image: supabase/studio:latest
    restart: unless-stopped
    ports:
      - "54323:3000"
    env_file:
      - .env.docker-compose
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_PUBLIC_ANON_KEY: ${SUPABASE_ANON_KEY}
    depends_on:
      - supabase-rest
